### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by byq-luo** [swhan0329/VDL_speed_estimation#2]
Could you tell me the format of luLine and ldLine, or can you provide the main.py file and the corresponding video  source file, thank you. Contact me：luozhongbin2015@gmail.com

**Comment by swhan0329** [comment]
Hello, @byq-luo.

This code will help you.

For example, I set the VDLs information like this..
```python
VDL = np.array([[x1,y1],[x2,y2],[x3,y3],[x4,y4],[x5,y5],[x6,y6],[x7,y7],[x8,y8]], np.int32)
```

and then luLine, ldLine, ruLine, rdLine can define like this.

```python
luLine = [(VDL[0][0],VDL[0][1]), (VDL[1][0],VDL[1][1])]
ldLine = [(VDL[2][0],VDL[2][1]), (VDL[3][0],VDL[3[1])]
ruLine = [(VDL[4][0],VDL[4][1]), (VDL[5][0],VDL[5][1])]
rdLine = [(VDL[6][0],VDL[6][1]), (VDL[7][0],VDL[7][1])]
```
