### ISSUE TITLE
driving_lane

### ISSUE THREAD

**Issue by byq-luo** [swhan0329/VDL_speed_estimation#3]
Thank you very much for your reply, how is driving_lane determined? I am a rookie, can I provide all the files of the code, thank you again, I am very interested in your research. Contact me：luozhongbin2015@gmail.com

**Comment by swhan0329** [comment]
Hello, @byq-luo
Thank you for your attention.
driving_lane is the same format as VDL information. 

Actually, the main code is our company property, so I can't share it with you.
Sorry for that.

**Comment by byq-luo** [comment]
> Hello, @byq-luo
> Thank you for your attention.
> driving_lane is the same format as VDL information.
> 
> Actually, the main code is our company property, so I can't share it with you.
> Sorry for that.

Thank you
